using System.Collections.Generic;

namespace Lexi.Core.Api.Services.Foundations.TelegramHandles
{
    public class WordsToLearn : IWordsToLearn
    {
        public List<(string, string, string)> NewWordsToLearn()
        {
            return new List<(string, string, string)>
{
    ("abandon", "to leave behind; to give up", "😔"),
    ("abundant", "plentiful; more than enough", "😊"),
    ("accelerate", "to speed up", "🚀"),
    ("accessible", "easily reached or approached", "🚶"),
    ("accommodate", "to provide space or room for", "🏠"),
    ("accompany", "to go along with", "👫"),
    ("accumulate", "to gather or collect", "📈"),
    ("acknowledge", "to recognize; to admit", "🙋"),
    ("adequate", "sufficient; enough", "👍"),
    ("adjust", "to adapt or change", "⚙️"),
    ("adventure", "an exciting or unusual experience", "🌍"),
    ("aggressive", "assertive; ready to attack", "👊"),
    ("alternative", "one of two or more options", "🔄"),
    ("amplify", "to make louder or stronger", "🔊"),
    ("analyze", "to examine closely", "🔍"),
    ("ancestor", "a person from whom one is descended", "👴"),
    ("anticipate", "to expect or foresee", "🔮"),
    ("anxiety", "nervousness or unease", "😟"),
    ("apparent", "clearly visible or understood", "👀"),
    ("appreciate", "to value or admire", "😊"),
    ("appropriate", "suitable or proper", "👌"),
    ("approximate", "nearly accurate", "🎯"),
    ("arbitrary", "based on random choice", "🎲"),
    ("assemble", "to gather together", "🛠️"),
    ("assert", "to state with confidence", "💪"),
    ("assess", "to evaluate or estimate", "📝"),
    ("assistance", "help or support", "🤝"),
    ("associate", "to connect or join", "🔗"),
    ("assume", "to take for granted; to suppose", "🤔"),
    ("assure", "to make certain or confident", "👍"),
    ("attribute", "a quality or characteristic", "🌟"),
    ("authorize", "to give official approval", "✅"),
    ("automate", "to operate with minimal human intervention", "🤖"),
    ("awkward", "clumsy or uncomfortable", "😬"),
    ("benevolent", "kind and generous", "👼"),
    ("bias", "prejudice in favor of or against something", "🤐"),
    ("boast", "to brag or show off", "💪"),
    ("boundary", "a dividing line or limit", "⛔"),
    ("calculate", "to determine by reasoning", "🧮"),
    ("capacity", "the maximum amount that something can contain", "📊"),
    ("capture", "to catch or seize", "📸"),
    ("category", "a group of similar things", "📦"),
    ("cease", "to stop; to come to an end", "⏹️"),
    ("chaotic", "in a state of complete disorder", "😵"),
    ("circumstance", "a fact or condition connected with an event", "🔄"),
    ("clarify", "to make clear or understandable", "🔍"),
    ("coincide", "to occur at the same time", "⏰"),
    ("collaborate", "to work together", "🤝"),
    ("commence", "to begin or start", "🎉"),
    ("commit", "to pledge or dedicate", "💍"),
    ("communicate", "to convey or exchange information", "📞"),
    ("compensate", "to make up for; to repay", "💰"),
    ("competent", "capable; skilled", "👩‍🎓"),
    ("complement", "to complete or enhance", "🌟"),
    ("complicate", "to make more difficult or intricate", "🤯"),
    ("comprehensive", "covering or including everything", "📚"),
    ("comprise", "to consist of; to be made up of", "🎁"),
    ("conceal", "to hide or keep secret", "🙈"),
    ("concede", "to admit or acknowledge", "🤷"),
    ("conceive", "to form a notion or idea", "💡"),
    ("concept", "an abstract idea or general notion", "🧠"),
    ("conclude", "to bring to an end; to finish", "🔚"),
    ("concurrent", "occurring at the same time", "⏳"),
    ("confident", "having faith in oneself; self-assured", "😎"),
    ("conflict", "a struggle or clash", "⚔️"),
    ("conform", "to comply with rules or standards", "🔄"),
    ("confront", "to face or challenge", "😤"),
    ("confuse", "to make unclear or perplexed", "😵"),
    ("congregate", "to gather together in a crowd", "👥"),
    ("consequence", "a result or effect", "🎯"),
    ("conservative", "favoring traditional values", "👴"),
    ("consistent", "unchanging; steady", "🔄"),
    ("console", "to comfort or soothe", "🤗"),
    ("conspire", "to plan secretly with others", "🤫"),
    ("constraint", "a limitation or restriction", "🚫"),
    ("consume", "to use up; to devour", "🍽️"),
    ("contemplate", "to consider deeply", "🤔"),
    ("contend", "to compete; to assert", "🥊"),
    ("context", "the circumstances or setting surrounding something", "🔍"),
    ("contradict", "to assert the opposite of what someone else says", "🤥"),
    ("contrast", "to compare in order to show differences", "🔄"),
    ("contribute", "to give or donate", "🎁"),
    ("controversial", "causing disagreement or debate", "🤔"),
    ("convince", "to persuade or win over", "🤝"),
    ("cooperate", "to work together toward a common goal", "🤝"),
    ("correlate", "to have a mutual relationship", "🔄"),
    ("correspond", "to match or be equivalent to", "📨"),
    ("counteract", "to neutralize or cancel the effect of", "🚫"),
            ("crucial", "extremely important; essential", "🔑"),
    ("cumbersome", "clumsy or difficult to manage", "🤦"),
    ("curious", "eager to learn or know", "🔍"),
    ("decipher", "to interpret or decode", "🔍"),
    ("decline", "to refuse or deteriorate", "⬇️"),
    ("dedicate", "to devote time or effort to a particular task", "🎯"),
    ("deficit", "a shortage or inadequacy", "💰"),
    ("definite", "clear and certain", "✅"),
    ("deliberate", "done consciously and intentionally", "🤔"),
    ("demographic", "relating to population characteristics", "📊"),
    ("denote", "to be a sign or indication of", "🚩"),
    ("depict", "to represent or portray", "🎨"),
    ("derive", "to obtain or receive from a source", "🔄"),
    ("designate", "to appoint or assign", "🎯"),
    ("despite", "in spite of; notwithstanding", "🤷"),
    ("detect", "to discover or identify", "🔍"),
    ("deviate", "to depart from the norm", "🚶"),
    ("devise", "to invent or create", "💡"),
    ("devote", "to dedicate or commit", "👍"),
    ("differentiate", "to recognize or express the difference between", "🔄"),
    ("diminish", "to make or become less", "⬇️"),
    ("discern", "to perceive or recognize", "👀"),
    ("discreet", "careful or cautious in one's speech or actions", "🤫"),
    ("discrete", "separate and distinct", "🔍"),
    ("disperse", "to scatter or distribute", "🌬️"),
    ("dispose", "to arrange or deal with", "🗑️"),
    ("distinct", "clearly different or separate", "🔍"),
    ("distract", "to divert one's attention", "🙈"),
    ("diverse", "varied or differing", "🔄"),
    ("dominant", "exercising control or influence", "👑"),
    ("dynamic", "characterized by constant change or activity", "🔄"),
    ("earnest", "showing sincere and intense conviction", "🙏"),
    ("eclipse", "to overshadow or surpass", "🌒"),
    ("edify", "to instruct or enlighten", "📚"),
    ("efficacy", "the ability to produce a desired result", "🎯"),
    ("elaborate", "involving many carefully arranged parts; detailed", "🔍"),
    ("elusive", "difficult to find, catch, or achieve", "🔍"),
    ("embrace", "to accept or support willingly and enthusiastically", "🤗"),
    ("emerge", "to become visible or known", "👀"),
    ("empirical", "based on observation or experience", "🔍"),
    ("enable", "to make possible or achievable", "🔓"),
    ("encounter", "to unexpectedly experience or be faced with", "🤝"),
    ("endeavor", "a serious attempt or effort", "💪"),
    ("endorse", "to publicly support or approve", "👍"),
    ("endow", "to provide with a quality or ability", "💡"),
    ("endure", "to suffer patiently; to withstand", "😣"),
    ("enhance", "to improve or augment", "🌟"),
    ("enlighten", "to provide insight or knowledge", "💡"),
    ("entail", "to involve as a necessary condition or consequence", "🔄"),
    ("enterprise", "a project or undertaking, typically one that is difficult or requires effort", "🏭"),
    ("entice", "to attract or tempt by offering pleasure or advantage", "🤤"),
    ("entity", "something that exists as a separate unit", "🌐"),
    ("envision", "to imagine or visualize", "👓"),
    ("ephemeral", "lasting for a very short time", "⏳"),
    ("equivocate", "to use ambiguous language to conceal the truth", "🤐"),
    ("erratic", "unpredictable or irregular in movement or behavior", "🔄"),
    ("essence", "the intrinsic nature or indispensable quality of something", "🌟"),
    ("establish", "to set up or create", "🏗️"),
    ("esteem", "to regard with respect or admiration", "👏"),
    ("euphoria", "a feeling of intense excitement or happiness", "😄"),
    ("evaluate", "to assess or judge the value or quality of", "📝"),
    ("evoke", "to bring or recall to the conscious mind", "🤔"),
    ("exemplify", "to serve as a typical example of", "🌟"),
    ("exhaustive", "including or considering all elements or aspects", "📚"),
    ("exotic", "originating in or characteristic of a distant foreign country", "🌴"),
    ("expand", "to become larger in size or volume", "🔍"),
    ("expedite", "to make happen sooner or be accomplished more quickly", "⏩"),
    ("expertise", "specialized knowledge or skill", "🎓"),
    ("exploit", "to make full use of and derive benefit from", "🛠️"),
    ("exposure", "the state of being subjected to contact with something", "👀"),
    ("exquisite", "extremely beautiful and delicate", "💖"),
    ("extensive", "covering or affecting a large area", "🌐"),
    ("extract", "to remove or take out", "🔍"),
    ("facilitate", "to make an action or process easier", "🛣️"),
    ("fantasy", "the product of imagining impossible or improbable things", "🧚"),
    ("fathom", "to understand thoroughly", "🤔"),
    ("feasible", "capable of being done or carried out", "👍"),
    ("feat", "an achievement that requires great courage, skill, or strength", "🏆"),
    ("fervent", "having or displaying a passionate intensity", "🔥"),
    ("fluctuate", "to rise and fall irregularly in number or amount", "🔄"),
    ("forge", "to create or develop through effort", "🔨"),
    ("formulate", "to create or devise methodically", "📝"),
    ("fortify", "to strengthen or invigorate", "🏰")};
        }
    }
}

