name: Excel.Importer Build Pipline
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checking out
      uses: actions/checkout@v2
    - name: Setting up .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
        include-prerelease: false
    - name: Restoring
      run: dotnet restore
    - name: Building
      run: dotnet build --no-restore
    - name: Testing
      run: dotnet test --no-build --verbosity normal
